export { default as UsersPanel } from './UsersPanel';
export { default as ProductPanel } from './ProductPanel';
export { default as CreateUser } from './CreateUser';
export { default as SimpleNav } from './SimpleNav';
export { default as DataTableUsers } from './DataTableUsers';
export { default as CreateProduct } from './CreateProduct';
export { default as DataTableProducts } from './DataTableProducts';
export { default as UpdateProduct } from './UpdateProduct';
export { default as ProductActions } from './ProductActions';
